services:
  github-archiver:
    image: ghcr.io/fa0311/github-archiver:latest-scheduler
    container_name: github-archiver
    environment:
      GH_TOKEN: ${GH_TOKEN}
      TZ: ${TZ:-UTC}
    volumes:
      - ./schedule.json:/app/schedule.json:ro
      - ./archives:/app/archives
      - github-archiver-data:/app/data

volumes:
  github-archiver-data:
